from django.urls import path
from homeapp.views import (
    home_index,
    tariffs_view,
    team_view,
    practices_view,
    rabotaem_view,
    polnomochiya_view,
    tayna_view,
    soglashenie_view,
    varianty_view,
    privicy_view,
    download_resume,
    get_individual_service_list,
    get_criminal_defense_detail,
    get_civil_defense_detail,
    get_inheritance_detail,
    get_migration_detail,
    get_traffic_accident_detail,
    get_license_revocation_detail,
    get_family_matters_detail,
    get_individual_bankruptcy_detail,
    get_consumer_protection_detail,
    get_land_disputes_detail,
    get_debt_recovery_detail,
    get_medical_detail,
    get_enforcement_lawyer_detail,
    get_appeals_detail,
    get_administrative_penalties_detail,
    get_online_consultation_detail,
    get_legal_service_list,
    get_insolvecy_support_detail,
    get_complex_support_detail,
    get_news_list,
    news_detail,
    PracticeDetailView,
    ReviewListView,
    cases_filter_view,
)


app_name = 'homeapp'
urlpatterns = [
    path('', home_index, name='index'),
    path('tariffs/', tariffs_view, name='tariffs'),
    path('team/', team_view, name='team'),
    path('cases/', practices_view, name='cases'),
    path('kak-my-rabotaem/', rabotaem_view, name='rabotaem'),
    path('polnomochiya-advokata/', polnomochiya_view, name='polnomochiya'),
    path('advokatskaya-tayna/', tayna_view, name='tayna'),
    path('soglashenie-i-order/', soglashenie_view, name='soglashenie'),
    path('varianty-voznagrozhdeniya/', varianty_view, name='varianty'),
    path('privicy/', privicy_view, name='privicy'),
    path('download/<path:file_path>', download_resume, name='download'),
    path('individual-service-list/', get_individual_service_list, name='individual_service_list'),
    path('individual-service-list/criminal-defense/', get_criminal_defense_detail, name='criminal_defense'),
    path('individual-service-list/civil-defense/', get_civil_defense_detail, name='civil_defense'),
    path('individual-service-list/inheritance/', get_inheritance_detail, name='inheritance'),
    path('individual-service-list/migration/', get_migration_detail, name='migration'),
    path('individual-service-list/traffic-accident/', get_traffic_accident_detail, name='traffic_accident'),
    path('individual-service-list/license-revocation/', get_license_revocation_detail, name='license_revocation'),
    path('individual-service-list/family-matters/', get_family_matters_detail, name='family_matters'),
    path('individual-service-list/individual-bankruptcy/', get_individual_bankruptcy_detail, name='individual_bankruptcy'),
    path('individual-service-list/consumer-protection/', get_consumer_protection_detail, name='consumer_protection'),
    path('individual-service-list/land-disputes/', get_land_disputes_detail, name='land_disputes'),
    path('individual-service-list/debt-recovery/', get_debt_recovery_detail, name='debt_recovery'),
    path('individual-service-list/medical/', get_medical_detail, name='medical'),
    path('individual-service-list/enforcement-lawyer/', get_enforcement_lawyer_detail, name='enforcement_lawyer'),
    path('individual-service-list/appeals/', get_appeals_detail, name='appeals'),
    path('individual-service-list/administrative-penalties/', get_administrative_penalties_detail, name='administrative_penalties'),
    path('individual-service-list/online-consultation/', get_online_consultation_detail, name='online_consultation'),
    path('legal-service-list/', get_legal_service_list, name='legal_service_list'),
    path('legal-service-list/insolvency-support/', get_insolvecy_support_detail, name='insolvecy_support'),
    path('legal-service-list/complex-support/', get_complex_support_detail, name='complex_support'),
    path('news-list/', get_news_list, name='news_list'),
    path('news_<slug:slug>/', news_detail, name='news_detail'),
    path('practices/<int:pk>/', PracticeDetailView.as_view(), name='practice_detail'),
    path('reviews/', ReviewListView.as_view(), name='reviews'),
    path('cases/filter/', cases_filter_view, name='cases_filter'),
]
