# Generated by Django 4.2 on 2024-10-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['my_order'], 'verbose_name': 'Партнера', 'verbose_name_plural': 'Партнеры'},
        ),
        migrations.AddField(
            model_name='partner',
            name='my_order',
            field=models.IntegerField(db_index=True, default=1, verbose_name='Порядок'),
            preserve_default=False,
        ),
    ]
