# Generated by Django 5.2 on 2025-04-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_partnerphoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consultation',
        ),
    ]
