# Generated by Django 5.2 on 2025-04-13 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_delete_consultation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
