# Generated by Django 5.2 on 2025-04-13 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_delete_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='work_place',
        ),
        migrations.RemoveField(
            model_name='practiceinstance',
            name='work_place',
        ),
    ]
