# Generated by Django 5.2 on 2025-04-19 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_remove_partner_work_place_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practicecategory',
            options={'verbose_name': 'категорию практики', 'verbose_name_plural': 'Категории практики'},
        ),
        migrations.AddField(
            model_name='news',
            name='video_link',
            field=models.URLField(blank=True, verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='practiceinstance',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.practicecategory', verbose_name='категория практики'),
        ),
    ]
