# Generated by Django 5.2 on 2025-04-19 20:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0007_alter_practicecategory_options_news_video_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Текст новости'),
        ),
    ]
