# Generated by Django 5.2 on 2025-04-20 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0008_alter_news_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceinstance',
            name='partner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practice', to='homeapp.partner'),
        ),
    ]
