# Generated by Django 5.2 on 2025-04-20 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0010_review_alter_practiceinstance_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Обложка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('audience', models.CharField(choices=[('legal', 'Юридические лица'), ('individual', 'Физические лица')], default='individual', max_length=20, verbose_name='Тип клиента')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория услуги',
                'verbose_name_plural': 'Категории услуг',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('title', 'Заголовок'), ('text', 'Текст'), ('image', 'Изображение'), ('list', 'Список'), ('quote', 'Цитата'), ('html', 'HTML (сырой код)')], default='text', max_length=20, verbose_name='Тип блока')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/blocks/', verbose_name='Изображение')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='homeapp.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Блок услуги',
                'verbose_name_plural': 'Блоки услуги',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='homeapp.servicecategory', verbose_name='Категория'),
        ),
    ]
