# Generated by Django 5.2 on 2025-04-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0013_article_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='hi', unique=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
    ]
