# Generated by Django 5.2 on 2025-04-20 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0014_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='homeapp.practiceinstance', verbose_name='Случай практики'),
        ),
    ]
