# Generated by Django 5.2 on 2025-04-21 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0015_video_practice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='min_context2',
            field=models.TextField(blank=True, verbose_name='Доп. поле 1'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='min_context3',
            field=models.TextField(blank=True, verbose_name='Доп. поле 2'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='min_context4',
            field=models.TextField(blank=True, verbose_name='Доп. поле 3'),
        ),
        migrations.AlterField(
            model_name='practiceinstance',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.practicecategory', verbose_name='Категория практики'),
        ),
        migrations.AlterField(
            model_name='practiceinstance',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practice', to='homeapp.partner', verbose_name='Адвокат'),
        ),
        migrations.AlterField(
            model_name='practiceinstanceimage',
            name='practice_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='homeapp.practiceinstance'),
        ),
    ]
