# Generated by Django 5.2 on 2025-04-21 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0016_alter_partner_min_context2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo/', verbose_name='Meta Image (OG Image)'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo/', verbose_name='Meta Image (OG Image)'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='practiceinstance',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='practiceinstance',
            name='meta_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo/', verbose_name='Meta Image (OG Image)'),
        ),
        migrations.AddField(
            model_name='practiceinstance',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo/', verbose_name='Meta Image (OG Image)'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta Title'),
        ),
    ]
