# Generated by Django 5.2 on 2025-05-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0018_article_seo_keywords_news_seo_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/previews/', verbose_name='Изображение статьи'),
        ),
        migrations.AddField(
            model_name='news',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='news/previews/', verbose_name='Изображение новости'),
        ),
    ]
