# Generated by Django 5.2 on 2025-06-15 10:42

import ckeditor.fields
from django.db import migrations


def remove_orphaned_admin_logs(apps, schema_editor):
    LogEntry = apps.get_model('admin', 'LogEntry')
    User = apps.get_model('auth', 'User')
    valid_user_ids = User.objects.values_list('id', flat=True)
    LogEntry.objects.exclude(user_id__in=valid_user_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0020_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practiceinstance',
            name='circumstances',
            field=ckeditor.fields.RichTextField(verbose_name='Обстоятельства'),
        ),
        migrations.AlterField(
            model_name='practiceinstance',
            name='lawyer_position',
            field=ckeditor.fields.RichTextField(verbose_name='Позиция адвоката'),
        ),
        migrations.AlterField(
            model_name='practiceinstance',
            name='outcome',
            field=ckeditor.fields.RichTextField(verbose_name='Итог'),
        ),
        migrations.RunPython(remove_orphaned_admin_logs, reverse_code=migrations.RunPython.noop),
    ]
