# Generated by Django 5.2 on 2025-06-15 10:54

from django.db import migrations, models


def populate_my_order(apps, schema_editor):
    PracticeInstance = apps.get_model('homeapp', 'PracticeInstance')
    for i, instance in enumerate(PracticeInstance.objects.all().order_by('id'), start=1):
        instance.my_order = i
        instance.save(update_fields=['my_order'])


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0021_alter_practiceinstance_circumstances_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practiceinstance',
            options={
                'ordering': ['my_order'],
                'verbose_name': 'Случай практики',
                'verbose_name_plural': 'Случаи практики',
            },
        ),
        migrations.AddField(
            model_name='practiceinstance',
            name='my_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.RunPython(populate_my_order, reverse_code=migrations.RunPython.noop),
    ]
