# Generated by Django 5.2 on 2025-06-15 11:32

from django.db import migrations, models


def populate_my_order_for_service(apps, schema_editor):
    Service = apps.get_model('homeapp', 'Service')
    for index, service in enumerate(Service.objects.order_by('id'), start=1):
        service.my_order = index
        service.save(update_fields=['my_order'])


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0022_alter_practiceinstance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['my_order'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='service',
            name='my_order',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Порядок'),
            preserve_default=False,
        ),
        migrations.RunPython(populate_my_order_for_service, reverse_code=migrations.RunPython.noop),
    ]
