# Generated by Django 5.2 on 2025-10-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0023_alter_service_options_service_my_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('moscow', 'Москва'), ('ulsk', 'Ульяновск')], max_length=20, unique=True, verbose_name='Город')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон (с +7)')),
                ('phone_display', models.CharField(max_length=20, verbose_name='Телефон (для отображения)')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('map_link', models.URLField(verbose_name='Ссылка на карту')),
                ('telegram_link', models.URLField(blank=True, verbose_name='Ссылка на Telegram')),
                ('instagram_link', models.URLField(blank=True, verbose_name='Ссылка на Instagram')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
