# Generated by Django 5.2 on 2025-10-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0024_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='reviews_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на отзывы в Яндекс Навигаторе'),
        ),
    ]
