# Generated by Django 4.2 on 2024-04-11 16:56

from django.db import migrations, models
import homeapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=12)),
                ('status', models.CharField(choices=[('ДА', 'ПЕРЕЗВОНИЛИ'), ('НЕТ', 'НЕ ПЕРЕЗВОНИЛИ')], default='НЕТ', max_length=3)),
                ('date_application', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Заявки',
                'ordering': ['-date_application'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(verbose_name='Слаг поста')),
                ('text', models.TextField(verbose_name='Текст новости')),
                ('status', models.CharField(choices=[('Нет', 'Не опубликована'), ('Да', 'Опубликована')], default='Нет', max_length=3, verbose_name='Статус')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-create_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Фамилия Имя Отчество')),
                ('min_context1', models.TextField(verbose_name='Краткое описание для первой страницы')),
                ('min_context2', models.TextField(blank=True, verbose_name='Дополнительное поле короткого писания')),
                ('min_context3', models.TextField(blank=True, verbose_name='Дополнительное поле короткого писания')),
                ('min_context4', models.TextField(blank=True, verbose_name='Дополнительное поле короткого писания')),
                ('context', models.TextField(verbose_name='Полное описание')),
                ('photo', models.ImageField(upload_to='partners/', verbose_name='Фото')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Партнера',
                'verbose_name_plural': 'Партнеры',
                'ordering': ['-time_create'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('want_to', models.CharField(choices=[('option', '-- выбрать --'), ('option_1', 'Прохождение практики'), ('option_2', 'Стажировка'), ('option_3', 'Помощник юриста'), ('option_4', 'Юрист'), ('option_5', 'Адвокат')], default='option', max_length=20, verbose_name='Желаемая позиция')),
                ('education', models.CharField(max_length=100, verbose_name='Место учёбы')),
                ('experience', models.CharField(blank=True, max_length=255, verbose_name='Опыт работы')),
                ('mail', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('covering', models.TextField(blank=True, default=None, verbose_name='Сопроводительное письмо')),
                ('resume', models.FileField(blank=True, upload_to=homeapp.models.translit_filename, verbose_name='Резюме')),
                ('agree', models.BooleanField(verbose_name='Согласие с политикой')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи резюме')),
                ('status', models.CharField(choices=[('ДА', 'Просмотрено'), ('НЕТ', 'Не просмотрено')], default='НЕТ', max_length=3, verbose_name='Статус')),
            ],
            options={
                'verbose_name_plural': 'Резюме',
                'ordering': ['-date'],
            },
        ),
    ]
