# Generated by Django 4.2 on 2024-10-10 06:54

from django.db import migrations, models
import django.db.models.deletion
import homeapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Имя')),
                ('number', models.CharField(max_length=12, verbose_name='Телефон')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Ваш вопрос (необязательно)')),
                ('status', models.CharField(choices=[('ДА', 'ПЕРЕЗВОНИЛИ'), ('НЕТ', 'НЕ ПЕРЕЗВОНИЛИ')], default='НЕТ', max_length=3, verbose_name='Статус')),
                ('date_application', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
            ],
            options={
                'verbose_name_plural': 'Заявки',
                'ordering': ['-date_application'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(verbose_name='Слаг поста')),
                ('text', models.TextField(verbose_name='Текст новости')),
                ('status', models.CharField(choices=[('Нет', 'Не опубликована'), ('Да', 'Опубликована')], default='Нет', max_length=3, verbose_name='Статус')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-create_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Фамилия Имя Отчество')),
                ('work_place', models.CharField(blank=True, choices=[('moscow', 'Head office: Moscow'), ('ulyanovsk', 'Ulyanovsk branch')], default='moscow', max_length=32, null=True, verbose_name='Место деятельности')),
                ('min_context1', models.TextField(verbose_name='Краткое описание для первой страницы')),
                ('min_context2', models.TextField(blank=True, verbose_name='Дополнительное поле короткого писания')),
                ('min_context3', models.TextField(blank=True, verbose_name='Дополнительное поле короткого писания')),
                ('min_context4', models.TextField(blank=True, verbose_name='Дополнительное поле короткого писания')),
                ('context', models.TextField(verbose_name='Полное описание')),
                ('photo', models.ImageField(upload_to='partners/', verbose_name='Фото')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Партнера',
                'verbose_name_plural': 'Партнеры',
                'ordering': ['-time_create'],
            },
        ),
        migrations.CreateModel(
            name='PracticeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Наименование категории практики')),
                ('image', models.ImageField(blank=True, null=True, upload_to='practice_category/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Категорию практики',
                'verbose_name_plural': 'Категории практик',
            },
        ),
        migrations.CreateModel(
            name='PracticeInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_place', models.CharField(blank=True, choices=[('moscow', 'Head office: Moscow'), ('ulyanovsk', 'Ulyanovsk branch')], default='moscow', max_length=32, null=True, verbose_name='Принадлежность случая')),
                ('title', models.CharField(max_length=255, verbose_name='Название случая')),
                ('circumstances', models.TextField(verbose_name='Обстоятельства')),
                ('lawyer_position', models.TextField(verbose_name='Позиция адвоката')),
                ('outcome', models.TextField(verbose_name='Итог')),
                ('verdict_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на приговор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.practicecategory', verbose_name='Категория практики')),
            ],
            options={
                'verbose_name': 'Случай практики',
                'verbose_name_plural': 'Случаи практики',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('want_to', models.CharField(choices=[('option', '-- выбрать --'), ('option_1', 'Прохождение практики'), ('option_2', 'Стажировка'), ('option_3', 'Помощник юриста'), ('option_4', 'Юрист'), ('option_5', 'Адвокат')], default='option', max_length=20, verbose_name='Желаемая позиция')),
                ('education', models.CharField(max_length=100, verbose_name='Место учёбы')),
                ('experience', models.CharField(blank=True, max_length=255, verbose_name='Опыт работы')),
                ('mail', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('covering', models.TextField(blank=True, default=None, verbose_name='Сопроводительное письмо')),
                ('resume', models.FileField(blank=True, upload_to=homeapp.models.translit_filename, verbose_name='Резюме')),
                ('agree', models.BooleanField(verbose_name='Согласие с политикой')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи резюме')),
                ('status', models.CharField(choices=[('ДА', 'Просмотрено'), ('НЕТ', 'Не просмотрено')], default='НЕТ', max_length=3, verbose_name='Статус')),
            ],
            options={
                'verbose_name_plural': 'Резюме',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PracticeInstanceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='practice_instance_images/', verbose_name='Изображение')),
                ('practice_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='homeapp.practiceinstance', verbose_name='Случай практики')),
            ],
            options={
                'verbose_name': 'Изображение случая практики',
                'verbose_name_plural': 'Изображения случаев практики',
            },
        ),
    ]
