# Generated by Django 4.2 on 2024-04-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='work_place',
            field=models.CharField(blank=True, choices=[('moscow', 'Head office: Moscow'), ('ulyanonsk', 'Ulyanovsk branch')], default='moscow', max_length=32, null=True, verbose_name='Место деятельности'),
        ),
    ]
