# Generated by Django 4.2 on 2023-08-15 14:51

from django.db import migrations, models
import homeapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(verbose_name='Слаг поста')),
                ('text', models.TextField(verbose_name='Текст новости')),
                ('status', models.CharField(choices=[('Нет', 'Не опубликована'), ('Да', 'Опубликована')], default='Нет', max_length=3, verbose_name='Статус')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-create_datetime'],
            },
        ),
        migrations.AlterField(
            model_name='worker',
            name='resume',
            field=models.FileField(blank=True, upload_to=homeapp.models.translit_filename, verbose_name='Резюме'),
        ),
    ]
