# Generated by Django 4.2 on 2023-11-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_news_alter_worker_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Фамилия Имя Отчество')),
                ('min_context1', models.TextField(verbose_name='Краткое описание для первой страницы')),
                ('min_context2', models.TextField(blank=True, verbose_name='Дополнительное поле короткого писания')),
                ('min_context3', models.TextField(blank=True, verbose_name='Дополнительное поле короткого писания')),
                ('min_context4', models.TextField(blank=True, verbose_name='Дополнительное поле короткого писания')),
                ('context', models.TextField(verbose_name='Полное описание')),
                ('photo', models.ImageField(upload_to='partners/', verbose_name='Фото')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Партнера',
                'verbose_name_plural': 'Партнеры',
                'ordering': ['time_create'],
            },
        ),
    ]
