# Generated by Django 4.2 on 2024-10-13 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_alter_partner_options_partner_my_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='partner_photos/')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='Подпись к фото')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='homeapp.partner')),
            ],
        ),
    ]
