# Generated by Django 4.2 on 2024-06-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_partner_work_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='question',
            field=models.TextField(blank=True, null=True, verbose_name='Ваш вопрос (необязательно)'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='date_application',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='number',
            field=models.CharField(max_length=12, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('ДА', 'ПЕРЕЗВОНИЛИ'), ('НЕТ', 'НЕ ПЕРЕЗВОНИЛИ')], default='НЕТ', max_length=3, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='username',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='work_place',
            field=models.CharField(blank=True, choices=[('moscow', 'Head office: Moscow'), ('ulyanovsk', 'Ulyanovsk branch')], default='moscow', max_length=32, null=True, verbose_name='Место деятельности'),
        ),
    ]
