# Generated by Django 4.2 on 2024-06-28 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_consultation_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Наименование категории практики')),
                ('image', models.ImageField(upload_to='practice_category/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Категорию практики',
                'verbose_name_plural': 'Категории практик',
            },
        ),
        migrations.CreateModel(
            name='PracticeInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_place', models.CharField(blank=True, choices=[('moscow', 'Head office: Moscow'), ('ulyanovsk', 'Ulyanovsk branch')], default='moscow', max_length=32, null=True, verbose_name='Принадлежность случая')),
                ('title', models.CharField(max_length=255, verbose_name='Название случая')),
                ('circumstances', models.TextField(verbose_name='Обстоятельства')),
                ('lawyer_position', models.TextField(verbose_name='Позиция адвоката')),
                ('outcome', models.TextField(verbose_name='Итог')),
            ],
            options={
                'verbose_name': 'Случай практики',
                'verbose_name_plural': 'Случаи практики',
            },
        ),
        migrations.CreateModel(
            name='PracticeInstanceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='practice_instance_images/', verbose_name='Изображение')),
                ('practice_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='homeapp.practiceinstance', verbose_name='Случай практики')),
            ],
            options={
                'verbose_name': 'Изображение случая практики',
                'verbose_name_plural': 'Изображения случаев практики',
            },
        ),
    ]
