# Generated by Django 4.2 on 2024-06-28 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_practicecategory_practiceinstance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceinstance',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homeapp.practicecategory', verbose_name='Категория практики'),
            preserve_default=False,
        ),
    ]
