# Generated by Django 4.2 on 2024-06-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_practiceinstance_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='practice_category/', verbose_name='Изображение'),
        ),
    ]
