# Generated by Django 4.2 on 2024-07-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_alter_practicecategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceinstance',
            name='verdict_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на приговор'),
        ),
    ]
